export const listOfStates = [
    { code: "68", state: "Acre" },
    { code: "82", state: "Alagoas" },
    { code: "96", state: "Amapá" },
    { code: "92", state: "Amazonas" },
    { code: "71", state: "Bahia" },
    { code: "85", state: "Ceará" },
    { code: "61", state: "Distrito Federal" },
    { code: "27", state: "Espírito Santo" },
    { code: "62", state: "Goiás" },
    { code: "98", state: "Maranhão" },
    { code: "65", state: "Mato Grosso" },
    { code: "67", state: "Mato Grosso do Sul" },
    { code: "31", state: "Minas Gerais" },
    { code: "91", state: "Pará" },
    { code: "83", state: "Paraíba" },
    { code: "41", state: "Paraná" },
    { code: "81", state: "Pernambuco" },
    { code: "86", state: "Piauí" },
    { code: "21", state: "Rio de Janeiro" },
    { code: "84", state: "Rio Grande do Norte" },
    { code: "51", state: "Rio Grande do Sul" },
    { code: "69", state: "Rondônia" },
    { code: "95", state: "Roraima" },
    { code: "48", state: "Santa Catarina" },
    { code: "11", state: "São Paulo" },
    { code: "79", state: "Sergipe" },
    { code: "63", state: "Tocantins" },
];
