export const listOfStates = [
    { code: "68", name: "Acre" },
    { code: "82", name: "Alagoas" },
    { code: "96", name: "Amapá" },
    { code: "92", name: "Amazonas" },
    { code: "71", name: "Bahia" },
    { code: "85", name: "Ceará" },
    { code: "61", name: "Distrito Federal" },
    { code: "27", name: "Espírito Santo" },
    { code: "62", name: "Goiás" },
    { code: "98", name: "Maranhão" },
    { code: "65", name: "Mato Grosso" },
    { code: "67", name: "Mato Grosso do Sul" },
    { code: "31", name: "Minas Gerais" },
    { code: "91", name: "Pará" },
    { code: "83", name: "Paraíba" },
    { code: "41", name: "Paraná" },
    { code: "81", name: "Pernambuco" },
    { code: "86", name: "Piauí" },
    { code: "21", name: "Rio de Janeiro" },
    { code: "84", name: "Rio Grande do Norte" },
    { code: "51", name: "Rio Grande do Sul" },
    { code: "69", name: "Rondônia" },
    { code: "95", name: "Roraima" },
    { code: "48", name: "Santa Catarina" },
    { code: "11", name: "São Paulo" },
    { code: "79", name: "Sergipe" },
    { code: "63", name: "Tocantins" },
];
